### ISSUE TITLE
React DnD 2.0 umbrella

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-dnd#303]
- [x] Extract HTML5 backend into [react-dnd-html5-backend](https://github.com/gaearon/react-dnd-html5-backend)
- [ ] Add peer dependency on React 0.14
- [ ] Consider changing `connect*` to only work with DOM React elements so we don't need to depend on `react-dom`
- [ ] Update the examples to use React 0.14
- [ ] Update the documentation
- [ ] Add React DnD and HTML5 backend to cdnjs
- [ ] Remove `dist` from the repo but keep it on NPM

**Comment by gaearon** [comment]
Superseded by https://github.com/gaearon/react-dnd/pull/304.
