### ISSUE TITLE
0.8 umbrella

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-dnd#78]
- [x] Expose `DragLayerMixin`
- [x] Separate backend refactoring
- [x] Combine custom & experimental drag layer examples
- [x] Remove memoize TODO in HTML5 backend
- [x] Instead of `x` and `y`, figure out what we should keep in `DragLayer` state
- [X] Still allow legacy API
- [x] Document new APIs

**Comment by gaearon** [comment]
Done.
